#include<iostream.h>

void main()
{
	char cTemp[40],cBoard[8][9];
	int i,j,iCount;
	for(i=0;i<17;i++)
	{
		cin.getline(cTemp,39);
		if(i%2)
			for(j=0;cTemp[j]!='\0';j++)
				if(!((j-2)%4))
					cBoard[i/2][(j-2)/4]=cTemp[j];
	}
	iCount=0;
	cout<<"White: ";
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='K')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"K"<<char('a'+j)<<char('1'+i);
			}
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='Q')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"Q"<<char('a'+j)<<char('1'+i);
			}
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='R')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"R"<<char('a'+j)<<char('1'+i);
			}
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='B')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"B"<<char('a'+j)<<char('1'+i);
			}
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='N')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"N"<<char('a'+j)<<char('1'+i);
			}
	for(i=0;i<8;i++)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='P')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<char('a'+j)<<char('1'+i);
			}
	cout<<endl;
	iCount=0;
	cout<<"Black: ";
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='k')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"K"<<char('a'+j)<<char('1'+i);
			}
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='q')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"Q"<<char('a'+j)<<char('1'+i);
			}
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='r')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"R"<<char('a'+j)<<char('1'+i);
			}
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='b')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"B"<<char('a'+j)<<char('1'+i);
			}
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='n')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<"N"<<char('a'+j)<<char('1'+i);
			}
	for(i=7;i>=0;i--)
		for(j=0;j<8;j++)
			if(cBoard[7-i][j]=='p')
			{
				if(iCount)
					cout<<",";
				else
					iCount++;
				cout<<char('a'+j)<<char('1'+i);
			}
	cout<<endl;
}