// POJ 1518 - Problem Bee
// Model: claude-sonnet-5
//
// The hexagon centers form a triangular lattice generated by the two
// "flat-top" hex axial directions; a point's hexagon is exactly the
// nearest lattice point (the hexagons are the Voronoi cells of that
// lattice). We convert (x,y) to fractional axial coordinates (q,r) for a
// flat-top hex grid of "radius" s (x = 1.5*s*q, y = sqrt(3)*s*(r+q/2)),
// then use the standard cube-coordinate rounding to find the containing
// hex. Hex-to-hex distance on the lattice is the usual cube distance,
// and each hop between adjacent centers costs s*sqrt(3).
//
// Ambiguity settled via the discuss board (message 352941): when A and B
// land in the same hexagon, the answer is the straight-line distance
// dist(A,B), not dist(A,center)+dist(center,B) (5.000 vs 9.222 on the
// "9 1 4 5 1" sample line) -- i.e. the center-detour is skipped entirely
// when zero hex-to-hex hops are needed.
#include <cstdio>
#include <cmath>
#include <cstdlib>

static const double SQRT3 = 1.7320508075688772935;

struct Axial { long q, r; };

static void toAxial(double x, double y, double s, long &q, long &r) {
    double fq = (2.0 / 3.0) * x / s;
    double fr = y / (SQRT3 * s) - x / (3.0 * s);
    double fx = fq, fz = fr, fy = -fx - fz;
    double rx = floor(fx + 0.5), ry = floor(fy + 0.5), rz = floor(fz + 0.5);
    double dx = fabs(rx - fx), dy = fabs(ry - fy), dz = fabs(rz - fz);
    if (dx > dy && dx > dz) {
        rx = -ry - rz;
    } else if (dy > dz) {
        ry = -rx - rz;
    } else {
        rz = -rx - ry;
    }
    q = (long)rx;
    r = (long)rz;
}

static void center(long q, long r, double s, double &cx, double &cy) {
    cx = 1.5 * s * (double)q;
    cy = SQRT3 * s * ((double)r + (double)q / 2.0);
}

static long hexDist(long q1, long r1, long q2, long r2) {
    long x1 = q1, z1 = r1, y1 = -x1 - z1;
    long x2 = q2, z2 = r2, y2 = -x2 - z2;
    long dx = labs(x1 - x2), dy = labs(y1 - y2), dz = labs(z1 - z2);
    return (dx + dy + dz) / 2;
}

int main() {
    double s, ax, ay, bx, by;
    while (scanf("%lf %lf %lf %lf %lf", &s, &ax, &ay, &bx, &by) == 5) {
        if (s == 0 && ax == 0 && ay == 0 && bx == 0 && by == 0) break;

        long qa, ra, qb, rb;
        toAxial(ax, ay, s, qa, ra);
        toAxial(bx, by, s, qb, rb);

        double dab = hypot(ax - bx, ay - by);

        double ans;
        if (qa == qb && ra == rb) {
            ans = dab;
        } else {
            double cax, cay, cbx, cby;
            center(qa, ra, s, cax, cay);
            center(qb, rb, s, cbx, cby);
            double dA = hypot(ax - cax, ay - cay);
            double dB = hypot(bx - cbx, by - cby);
            long hd = hexDist(qa, ra, qb, rb);
            ans = dA + dB + (double)hd * s * SQRT3;
        }
        printf("%.3f\n", ans);
    }
    return 0;
}
