// POJ 2500 - Pia's Party
// Model: claude-sonnet-5
//
// Approach: the c candidate points, generated by (g*k) mod n for k=0..c-1,
// all lie on one circle of radius R=d/2. For four points on a circle in
// circular order with consecutive central angles a,b,c,e (a+b+c+e = 2*pi),
// the quadrilateral's area is R^2/2 * (sin a + sin b + sin c + sin e).
//
// Fix a diagonal (i,j) among the sorted (by angle) candidate points. It
// splits the quadrilateral into two triangles sharing that diagonal, and
// the area contributed by each side depends ONLY on the third vertex on
// that side (independent of the other side once i,j are fixed): for the
// left arc (i,j) we want b maximizing sin(theta_b-theta_i)+sin(theta_j-theta_b),
// and for the right arc (j,i+2pi) we want d maximizing
// sin(theta_d-theta_j)+sin(theta_{i+2pi}-theta_d).
// Writing x=theta_b-theta_i, y=theta_j-theta_b with x+y=S fixed (=theta_j-theta_i),
// sin x + sin y = 2 sin(S/2) cos((x-y)/2), maximized by minimizing |x-y|,
// i.e. by choosing the point whose angle is nearest the arc's bisector
// angle (theta_i+theta_j)/2. Since that bisector is monotonically
// increasing in j (i fixed), the optimal b is a monotonically
// non-decreasing function of j, and likewise for d (bisector
// (theta_j+theta_{i+2pi})/2, monotone increasing in j). So for fixed i,
// sweeping j forward, both b and d pointers only advance forward: O(c)
// per i, O(c^2) total.
//
// Positions are computed iteratively (p[k] = (p[k-1]+g) mod n) to avoid any
// need for 64-bit arithmetic, since p[k-1] < n <= 1e9 and g <= n <= 1e9 so
// p[k-1]+g < 2e9, which fits a 32-bit signed int.
//
// Statement ambiguity: none found; the discuss board mainly warns about pi
// precision (use acos(-1.0), not a truncated literal) and about avoiding
// overflow in the position generator, both handled above. Verified locally
// against an O(c^4) brute force (real 2D coordinates + shoelace over all
// 4-subsets) for small c, and against an O(c^3) diagonal+linear-scan cross
// check for larger c, including the board's own stress case (d=123,
// n=654321, c=123, g=542).

#include <cstdio>
#include <cmath>
#include <algorithm>
using namespace std;

static const double PI = acos(-1.0);
static const int MAXC = 1005;

int pos[MAXC];
double theta[2 * MAXC];
double sinT[2 * MAXC], cosT[2 * MAXC];

// sin(theta[a] - theta[b]) via the angle-subtraction identity, using
// precomputed sin/cos so the O(c^2) inner loop makes no trig calls at all.
static inline double sinDiff(int a, int b) {
    return sinT[a] * cosT[b] - cosT[a] * sinT[b];
}

int main() {
    int T;
    if (scanf("%d", &T) != 1) return 0;
    for (int tc = 1; tc <= T; ++tc) {
        int d, n, c, g;
        scanf("%d %d %d %d", &d, &n, &c, &g);

        pos[0] = 0;
        for (int k = 1; k < c; ++k) {
            int p = pos[k - 1] + g;
            if (p >= n) p -= n;
            pos[k] = p;
        }
        sort(pos, pos + c);

        for (int k = 0; k < c; ++k) theta[k] = 2.0 * PI * (double)pos[k] / (double)n;
        for (int k = 0; k < c; ++k) theta[k + c] = theta[k] + 2.0 * PI;
        for (int k = 0; k < 2 * c; ++k) { sinT[k] = sin(theta[k]); cosT[k] = cos(theta[k]); }

        double R = d / 2.0;
        double best = 0.0;

        for (int i = 0; i < c; ++i) {
            int b = i + 1;
            int dd = i + 2;
            int k = i + c; // "wrapped" copy of i
            for (int j = i + 2; j <= i + c - 2; ++j) {
                // advance b within (i, j)
                double mid1 = (theta[i] + theta[j]) * 0.5;
                while (b + 1 <= j - 1 && fabs(theta[b + 1] - mid1) < fabs(theta[b] - mid1)) ++b;
                if (b >= j) b = j - 1; // safety clamp (shouldn't trigger)
                if (b <= i) b = i + 1;

                // advance dd within (j, k)
                if (dd <= j) dd = j + 1;
                double mid2 = (theta[j] + theta[k]) * 0.5;
                while (dd + 1 <= k - 1 && fabs(theta[dd + 1] - mid2) < fabs(theta[dd] - mid2)) ++dd;
                if (dd >= k) dd = k - 1;
                if (dd <= j) dd = j + 1;

                double sum = sinDiff(b, i) + sinDiff(j, b)
                           + sinDiff(dd, j) + sinDiff(k, dd);
                double area = 0.5 * R * R * sum;
                if (area > best) best = area;
            }
        }

        printf("Scenario #%d:\n%.6f\n\n", tc, best);
    }
    return 0;
}
