// POJ 2741 - Colored Cubes
// Model: claude-sonnet-5
//
// Face numbering (Figure 5/6): 0=front,1=right,2=top,3=bottom,4=left,5=back
// (problem's 1..6 shifted to 0-indexed). The 24 rotation permutations of a
// cube were generated by enumerating the 24 proper (det=+1) signed
// permutation matrices acting on the six face-normal unit vectors and
// reading off, for each rotation, which original face ends up at each
// position. Because a common rotation applied to every cube in the set does
// not change the multiset of colors landing on each of the 6 positions
// (across the whole set), the minimum repaint count only depends on the
// *relative* orientation between cubes. So cube 0's orientation can be fixed
// to identity and every other cube's orientation enumerated over all 24
// rotations (24^(n-1) <= 24^3 = 13824 combinations for n<=4), each checked
// in O(6) by taking, for every one of the 6 positions, the most frequent
// color among the n (rotated) cubes -- repainting to that color costs
// n - maxFrequency at that position, and positions are independent once the
// per-cube rotation is fixed.
#include <cstdio>
#include <string>
#include <map>
#include <vector>
using namespace std;

static const int PERM[24][6] = {
    {0,1,2,3,4,5},
    {0,2,4,1,3,5},
    {0,3,1,4,2,5},
    {0,4,3,2,1,5},
    {1,0,3,2,5,4},
    {1,2,0,5,3,4},
    {1,3,5,0,2,4},
    {1,5,2,3,0,4},
    {2,0,1,4,5,3},
    {2,1,5,0,4,3},
    {2,4,0,5,1,3},
    {2,5,4,1,0,3},
    {3,0,4,1,5,2},
    {3,1,0,5,4,2},
    {3,4,5,0,1,2},
    {3,5,1,4,0,2},
    {4,0,2,3,5,1},
    {4,2,5,0,3,1},
    {4,3,0,5,2,1},
    {4,5,3,2,0,1},
    {5,1,3,2,4,0},
    {5,2,1,4,3,0},
    {5,3,4,1,2,0},
    {5,4,2,3,1,0}
};

int n;
int cube[4][6];
int best;

// allRot[c][r][pos] = color of cube c, position pos, after rotation r.
int allRot[4][24][6];

int cnt[64]; // reset lazily via touched list, indexed by color id (<= 24 colors per dataset)

int main() {
    while (scanf("%d", &n) == 1) {
        if (n == 0) break;
        map<string,int> colorId;
        for (int c = 0; c < n; c++) {
            for (int i = 0; i < 6; i++) {
                char buf[64];
                scanf("%s", buf);
                string s(buf);
                map<string,int>::iterator it = colorId.find(s);
                int id;
                if (it == colorId.end()) {
                    id = (int)colorId.size();
                    colorId[s] = id;
                } else {
                    id = it->second;
                }
                cube[c][i] = id;
            }
        }
        for (int c = 0; c < n; c++) {
            for (int r = 0; r < 24; r++) {
                const int *p = PERM[r];
                for (int i = 0; i < 6; i++) allRot[c][r][i] = cube[c][p[i]];
            }
        }
        for (int i = 0; i < 64; i++) cnt[i] = 0;

        best = 1000000;
        if (n == 1) {
            best = 0;
        } else {
            // cube 0's orientation is fixed to identity (rotation index 0):
            // a common rotation applied to every cube does not change the
            // per-position color multiset across the set, so only relative
            // orientation matters. Enumerate rotations for cubes 1..n-1.
            int idx[4];
            for (int i = 1; i < n; i++) idx[i] = 0;
            bool done = false;
            while (!done) {
                int total = 0;
                for (int pos = 0; pos < 6; pos++) {
                    int touched[4];
                    int v = allRot[0][0][pos];
                    cnt[v]++;
                    touched[0] = v;
                    int mx = cnt[v];
                    for (int c = 1; c < n; c++) {
                        v = allRot[c][idx[c]][pos];
                        int f = ++cnt[v];
                        touched[c] = v;
                        if (f > mx) mx = f;
                    }
                    for (int c = 0; c < n; c++) cnt[touched[c]] = 0;
                    total += (n - mx);
                }
                if (total < best) best = total;
                // increment odometer over idx[1..n-1], base 24
                int pos2 = n - 1;
                while (pos2 >= 1) {
                    idx[pos2]++;
                    if (idx[pos2] < 24) break;
                    idx[pos2] = 0;
                    pos2--;
                }
                if (pos2 < 1) done = true;
            }
        }
        printf("%d\n", best);
    }
    return 0;
}
