// POJ 1395 - Cog-Wheels
// Model: claude-sonnet-5
//
// Approach: A gear train built from wheels c1..cn realizes exactly the
// ratios that lie in the multiplicative group of positive rationals
// generated by {ci/cj : i,j}, which equals the group generated by the
// differences (in prime-exponent-vector space) u_i - u_1, where u_i is
// the prime factorization exponent vector of c_i. This is an integer
// lattice-membership problem: factor every c_i (and every query a,b)
// into primes, reduce the generator vectors u_i-u_1 to a triangular
// integer basis via pairwise extended-gcd column elimination (a Hermite
// Normal Form style reduction), then test whether the target vector
// log(a)-log(b) is an integer combination of that basis.
//
// Statement ambiguity: none beyond the usual "read exact counts, honor
// the blank line after every scenario" formatting, confirmed against
// the sample. The discuss board (message 358922) independently confirms
// this exact HNF / integer-linear-system formulation is the intended
// solution.
#include <cstdio>
#include <map>
#include <vector>
#include <algorithm>
using namespace std;
typedef long long ll;
typedef map<int, ll> Vec;

int spf[10001];

void sieve() {
    for (int i = 2; i <= 10000; i++) {
        if (spf[i] == 0) {
            for (int j = i; j <= 10000; j += i)
                if (spf[j] == 0) spf[j] = i;
        }
    }
}

Vec factorize(int x) {
    Vec v;
    while (x > 1) {
        int p = spf[x];
        int c = 0;
        while (x % p == 0) { x /= p; c++; }
        v[p] += c;
    }
    return v;
}

void addScaled(Vec &target, const Vec &src, ll scale) {
    for (Vec::const_iterator it = src.begin(); it != src.end(); ++it)
        target[it->first] += scale * it->second;
    for (Vec::iterator it = target.begin(); it != target.end();) {
        if (it->second == 0) {
            Vec::iterator nxt = it; ++nxt;
            target.erase(it);
            it = nxt;
        } else ++it;
    }
}

Vec subtractVec(const Vec &a, const Vec &b) {
    Vec r = a;
    addScaled(r, b, -1);
    return r;
}

ll extgcd(ll a, ll b, ll &x, ll &y) {
    if (b == 0) { x = 1; y = 0; return a; }
    ll x1, y1;
    ll g = extgcd(b, a % b, x1, y1);
    x = y1;
    y = x1 - (a / b) * y1;
    return g;
}

ll getv(const Vec &v, int key) {
    Vec::const_iterator it = v.find(key);
    if (it == v.end()) return 0;
    return it->second;
}

int main() {
    sieve();
    int T;
    if (scanf("%d", &T) != 1) return 0;
    for (int tc = 1; tc <= T; tc++) {
        int n; scanf("%d", &n);
        vector<int> c(n);
        for (int i = 0; i < n; i++) scanf("%d", &c[i]);
        vector<Vec> u(n);
        for (int i = 0; i < n; i++) u[i] = factorize(c[i]);
        vector<Vec> gens;
        for (int i = 1; i < n; i++) gens.push_back(subtractVec(u[i], u[0]));

        vector<Vec> active = gens;
        vector<pair<int, Vec> > basis;

        vector<int> cols;
        {
            map<int, bool> colset;
            for (size_t i = 0; i < gens.size(); ++i)
                for (Vec::iterator it = gens[i].begin(); it != gens[i].end(); ++it)
                    colset[it->first] = true;
            for (map<int, bool>::iterator it = colset.begin(); it != colset.end(); ++it)
                cols.push_back(it->first);
        }
        sort(cols.begin(), cols.end());

        for (size_t ci2 = 0; ci2 < cols.size(); ++ci2) {
            int col = cols[ci2];
            vector<int> idxs;
            for (size_t i = 0; i < active.size(); ++i) {
                if (getv(active[i], col) != 0) idxs.push_back((int)i);
            }
            while (idxs.size() > 1) {
                int ia = idxs[0], ib = idxs[1];
                ll va = getv(active[ia], col), vb = getv(active[ib], col);
                ll x, y;
                ll g = extgcd(va, vb, x, y);
                Vec newA, newB;
                addScaled(newA, active[ia], x);
                addScaled(newA, active[ib], y);
                addScaled(newB, active[ia], vb / g);
                addScaled(newB, active[ib], -(va / g));
                active[ia] = newA;
                active[ib] = newB;
                idxs.erase(idxs.begin() + 1);
            }
            if (idxs.size() == 1) {
                int idx = idxs[0];
                basis.push_back(make_pair(col, active[idx]));
                active.erase(active.begin() + idx);
            }
        }

        printf("Scenario #%d:\n", tc);
        int m; scanf("%d", &m);
        for (int q = 0; q < m; q++) {
            int a, b; scanf("%d %d", &a, &b);
            Vec v = subtractVec(factorize(a), factorize(b));
            bool ok = true;
            for (size_t i = 0; i < basis.size() && ok; ++i) {
                int p = basis[i].first;
                ll val = getv(v, p);
                if (val == 0) continue;
                ll pivotVal = getv(basis[i].second, p);
                if (val % pivotVal != 0) { ok = false; break; }
                ll x = val / pivotVal;
                addScaled(v, basis[i].second, -x);
            }
            if (ok) {
                for (Vec::iterator it = v.begin(); it != v.end(); ++it)
                    if (it->second != 0) { ok = false; break; }
            }
            if (ok) printf("Gear ratio %d:%d can be realized.\n", a, b);
            else printf("Gear ratio %d:%d cannot be realized.\n", a, b);
        }
        printf("\n");
    }
    return 0;
}
