// POJ 3139 - Balancing the Scale
// Model: claude-sonnet-5
//
// The figure (images/3139_1.png) shows a plus/cross-shaped scale, not a
// simple two-pan balance: a horizontal beam carries X1..X4 left of the
// fulcrum and X5..X8 right of it, a vertical beam carries Y1..Y4 above
// the fulcrum and Y5..Y8 below it. Torque balance about the fulcrum
// gives exactly the two equations in the statement (coefficients
// 4,3,2,1 for the far-to-near arm of each beam, 1,2,3,4 for the
// near-to-far arm). We must count bijections from the 16 given distinct
// numbers to the 16 labeled slots satisfying both equations, then
// divide by the size of the shape's symmetry group.
//
// The "+" shape has the same symmetry as a square: the dihedral group
// D4 of order 8 (rotations by 0/90/180/270 degrees and 4 reflections),
// generated by a 90-degree rotation (which cyclically maps the West,
// North, East, South arms into one another, e.g. X1->Y1->X8->Y8->X1)
// and a mirror flip (which reverses one beam's arm order, e.g.
// X1<->X8, X2<->X7, ...). Every one of these 8 symmetries permutes the
// 16 slots with no fixed point other than the identity permutation, so
// since all 16 input numbers are distinct, no non-identity symmetry can
// map a valid assignment to itself: every valid assignment has an orbit
// of size exactly 8 under this group. Hence
//   answer = (number of raw valid bijections) / 8.
//
// Counting the raw bijections: for 4 distinct numbers, let h(v) be the
// number of the 4! permutations assigning them to coefficients
// {1,2,3,4} (the coefficient labels' own order doesn't matter, only the
// resulting multiset of weighted sums) that yield weighted sum v. For
// an 8-set S split into two disjoint 4-sets (W,E) representing one full
// equation (e.g. the X equation: W -> X1..X4, E -> X5..X8), the number
// of ways to realize that equation with S is
//   F(S) = sum over ordered 4/4 partitions (W,E) of S, sum_v h(W,v)*h(E,v).
// The raw total is then sum over 8-subsets S of F(S)*F(complement(S))
// (S = numbers used in the X equation, complement = the Y equation).
//
// Implementation: enumerate all C(16,4)=1820 four-element index subsets
// of the 16 input numbers; for each, compute its (value -> count)
// distribution over the 24 permutations (values collapse to <=24
// entries). Bucket all (subset, value) entries by value using a linked
// list per value (value range is bounded by 4*1024=4096 per beam side,
// so 0..10240 covers every possible weighted sum). Within each value's
// bucket, accumulate F[mask_i | mask_j] += count_i*count_j for every
// ordered pair of entries with disjoint masks (this bucketing is what
// makes the O(1820^2) worst case fast in practice, since only entries
// that actually share a sum value need to be paired, matching the
// approach several accepted solutions on the discuss board describe).
// Finally sum F[S]*F(complement of S) over all 8-subsets S and divide
// by 8.
//
// Verified against the sample (Case 1: 15227223), against a reference
// O(1820^2) direct double-loop implementation of the same formula on
// randomized inputs across the full value range, and under
// -fsanitize=address,undefined.
#include <cstdio>
#include <cstring>
#include <algorithm>
using namespace std;

typedef long long ll;

int a[16];

const int NSUB = 1820; // C(16,4)
const int MAXV = 10240; // 4*1024 + 3*1024 + 2*1024 + 1*1024, max possible weighted sum

int subMask[NSUB];
int subVal[NSUB][24];
int subCnt[NSUB][24];
int subLen[NSUB];

void buildSubsets() {
    int idx = 0;
    for (int i0 = 0; i0 < 16; i0++)
    for (int i1 = i0 + 1; i1 < 16; i1++)
    for (int i2 = i1 + 1; i2 < 16; i2++)
    for (int i3 = i2 + 1; i3 < 16; i3++) {
        int mask = (1 << i0) | (1 << i1) | (1 << i2) | (1 << i3);
        int v0 = a[i0], v1 = a[i1], v2 = a[i2], v3 = a[i3];
        int sums[24];
        int cnt = 0;
        int c[4] = {1, 2, 3, 4};
        do {
            sums[cnt++] = v0 * c[0] + v1 * c[1] + v2 * c[2] + v3 * c[3];
        } while (next_permutation(c, c + 4));
        sort(sums, sums + cnt);
        int len = 0;
        for (int k = 0; k < cnt; ) {
            int j = k;
            while (j < cnt && sums[j] == sums[k]) j++;
            subVal[idx][len] = sums[k];
            subCnt[idx][len] = j - k;
            len++;
            k = j;
        }
        subMask[idx] = mask;
        subLen[idx] = len;
        idx++;
    }
}

const int MAXE = NSUB * 24;
int bucketHead[MAXV + 1];
int entryNext[MAXE];
int entryMask[MAXE];
int entryCnt[MAXE];
int touched[MAXV + 1];
int nTouched;

ll F[1 << 16];

int main() {
    int caseNo = 0;
    while (true) {
        int first;
        if (scanf("%d", &first) != 1) break;
        if (first == 0) break;
        a[0] = first;
        for (int i = 1; i < 16; i++) scanf("%d", &a[i]);
        caseNo++;

        buildSubsets();

        memset(F, 0, sizeof(F));
        memset(bucketHead, -1, sizeof(bucketHead));
        nTouched = 0;
        int ecnt = 0;
        for (int i = 0; i < NSUB; i++) {
            int m = subMask[i];
            for (int k = 0; k < subLen[i]; k++) {
                int v = subVal[i][k];
                entryMask[ecnt] = m;
                entryCnt[ecnt] = subCnt[i][k];
                entryNext[ecnt] = bucketHead[v];
                if (bucketHead[v] == -1) touched[nTouched++] = v;
                bucketHead[v] = ecnt;
                ecnt++;
            }
        }

        // A single subset contributes at most one entry per distinct value,
        // so a bucket can never hold more than NSUB entries.
        static int emask[NSUB], ecntArr[NSUB];
        for (int t = 0; t < nTouched; t++) {
            int v = touched[t];
            int m = 0;
            for (int e = bucketHead[v]; e != -1; e = entryNext[e]) {
                emask[m] = entryMask[e];
                ecntArr[m] = entryCnt[e];
                m++;
            }
            for (int x = 0; x < m; x++) {
                int mx = emask[x], cx = ecntArr[x];
                for (int y = 0; y < m; y++) {
                    if (x == y) continue;
                    if (mx & emask[y]) continue;
                    F[mx | emask[y]] += (ll)cx * ecntArr[y];
                }
            }
        }

        ll raw = 0;
        int full = (1 << 16) - 1;
        for (int S = 0; S <= full; S++) {
            if (__builtin_popcount(S) != 8) continue;
            int comp = full ^ S;
            if (F[S] && F[comp]) raw += F[S] * F[comp];
        }

        ll ans = raw / 8;
        printf("Case %d: %lld\n", caseNo, ans);
    }
    return 0;
}
