// POJ 1143 - Number Game
// Model: claude-opus-5
//
// A position is the set of still-choosable numbers, all in [2,20], so it fits in
// a 19-bit mask (bit v-2 <-> number v).  The forbidden set F is the numerical
// semigroup generated by everything chosen so far; within [2,20] it is exactly
// the complement of the mask, and every number > 20 is forbidden (otherwise the
// position would list it).
//
// Choosing x replaces F by the semigroup generated by F u {x}, which is
// { k*x + s : k >= 1, s in F u {0} } u F -- closed because F itself is closed.
// So a number y survives the move iff no k >= 1 has y - k*x in {0} u F.  (Note
// 1 is never in F, since F is generated by numbers >= 2.)
//
// win(S) is then plain backward induction: S is winning iff some legal x leads
// to a losing position; the empty position loses.  Masks strictly shrink on
// every move, so a flat 2^19 memo table needs no ordering pass.
//
// Output note: the problem text says "Test case #m" but the sample -- and the
// judge -- want "Test Case #m" with a capital C.  A blank line follows every
// case, including the last.

#include <cstdio>

static char memo[1 << 19]; /* 0 = unknown, 1 = winning, 2 = losing */

static int applyMove(int mask, int x)
{
    int next = 0;
    int y;
    for (y = 2; y <= 20; ++y) {
        int r;
        int killed = 0;
        if (!((mask >> (y - 2)) & 1))
            continue;
        for (r = y - x; r >= 0; r -= x) {
            if (r == 0) { killed = 1; break; }         /* y is a multiple of x */
            if (r == 1) continue;                      /* 1 is never forbidden */
            if (!((mask >> (r - 2)) & 1)) { killed = 1; break; } /* r in F */
        }
        if (!killed)
            next |= 1 << (y - 2);
    }
    return next;
}

static int isWinning(int mask)
{
    int x;
    if (memo[mask])
        return memo[mask] == 1;
    memo[mask] = 2;
    for (x = 2; x <= 20; ++x) {
        if (!((mask >> (x - 2)) & 1))
            continue;
        if (!isWinning(applyMove(mask, x))) {
            memo[mask] = 1;
            break;
        }
    }
    return memo[mask] == 1;
}

int main(void)
{
    int n;
    int testCase = 0;
    while (scanf("%d", &n) == 1 && n != 0) {
        int mask = 0;
        int i, x;
        int first = 1;
        for (i = 0; i < n; ++i) {
            if (scanf("%d", &x) != 1)
                return 0;
            if (x >= 2 && x <= 20)
                mask |= 1 << (x - 2);
        }
        printf("Test Case #%d\n", ++testCase);
        for (x = 2; x <= 20; ++x) {
            if (!((mask >> (x - 2)) & 1))
                continue;
            if (isWinning(applyMove(mask, x)))
                continue;
            if (first) {
                printf("The winning moves are: %d", x);
                first = 0;
            } else {
                printf(" %d", x);
            }
        }
        if (first)
            printf("There's no winning move.\n");
        else
            printf("\n");
        printf("\n");
    }
    return 0;
}
