// POJ 2561 - Language Cardinality
// Model: claude-sonnet-5
//
// Approach: BFS over the set of reachable strings. Starting from the
// initial string, repeatedly try every replacement rule at every
// (possibly overlapping) occurrence of its left-hand side in each
// string already found, inserting newly produced strings into a
// visited set and a work queue. Stop as soon as the visited set
// exceeds 1000 distinct strings and report "Too many."; otherwise
// report the final set size once the queue empties.
//
// Statement ambiguity settled from the discuss board (message
// 27909 / 33489, thread on "abc" with rules "b"->"c", "cc"->"zz"):
// a rule may be applied to ANY string already generated by the
// grammar, not only to the original initial string -- that example
// yields the confirmed answer {"abc","acc","azz"} = 3, matching a
// BFS closure over the whole reachable set. The left-hand side may
// be the empty string, in which case it matches at every one of
// len+1 positions of the current string. Overlapping occurrences of
// a nonempty s1 are all considered separately (the search position
// advances by 1, not by |s1|), since each occurrence is a distinct
// possible replacement site and can yield a different result string.
//
// Performance: a rule like "a"->"aa" (s1 a substring of s2, so the
// replacement re-creates its own trigger inside itself) generates an
// infinite monotonically-growing chain of distinct strings with only
// one new child per BFS level, which makes the naive O(len) positions
// x O(len) substr-copy cost blow up to roughly O(len^3) summed over
// ~1000 levels before the 1000-cap is ever reached. This is
// mathematically guaranteed to produce more than 1000 distinct
// strings (w0 -> w1 -> w2 -> ... all different lengths), so it is
// detected directly: whenever a matched occurrence of s1 lies inside
// a rule whose s2 contains s1 as a substring with |s2|>|s1|, the
// language is immediately known to be infinite and "Too many." is
// reported without simulating the chain.
#include <string>
#include <vector>
#include <set>
#include <deque>
#include <iostream>
using namespace std;

int main() {
    string firstLine;
    if (!getline(cin, firstLine)) return 0;

    size_t p1 = firstLine.find('"');
    size_t p2 = firstLine.find('"', p1 + 1);
    string init = firstLine.substr(p1 + 1, p2 - p1 - 1);

    vector<string> lhs, rhs;
    string line;
    while (getline(cin, line)) {
        size_t q1 = line.find('"');
        if (q1 == string::npos) continue; // skip blank/stray lines
        size_t q2 = line.find('"', q1 + 1);
        size_t q3 = line.find('"', q2 + 1);
        size_t q4 = line.find('"', q3 + 1);
        if (q4 == string::npos) continue;
        lhs.push_back(line.substr(q1 + 1, q2 - q1 - 1));
        rhs.push_back(line.substr(q3 + 1, q4 - q3 - 1));
    }

    // Precompute which rules are "self-growing": applying them inside
    // a string that already contains a match reproduces s1 again
    // inside the freshly inserted text, so once such a rule is ever
    // applicable the language is provably infinite.
    vector<bool> growing(lhs.size());
    for (size_t r = 0; r < lhs.size(); ++r) {
        growing[r] = (rhs[r].size() > lhs[r].size()) &&
                     (rhs[r].find(lhs[r]) != string::npos);
    }

    set<string> visited;
    deque<string> work;
    visited.insert(init);
    work.push_back(init);

    bool tooMany = false;
    const size_t CAP = 1000;

    while (!work.empty() && !tooMany) {
        string cur = work.front();
        work.pop_front();

        for (size_t r = 0; r < lhs.size() && !tooMany; ++r) {
            const string &s1 = lhs[r];
            const string &s2 = rhs[r];
            if (s1.empty()) {
                if (growing[r]) {
                    // s1 is empty, so it always matches (rhs nonempty
                    // since growing requires |s2|>|s1|=0): infinite.
                    tooMany = true;
                    break;
                }
                for (size_t i = 0; i <= cur.size(); ++i) {
                    string nxt = cur.substr(0, i) + s2 + cur.substr(i);
                    if (visited.insert(nxt).second) {
                        work.push_back(nxt);
                        if (visited.size() > CAP) { tooMany = true; break; }
                    }
                }
            } else {
                size_t pos = cur.find(s1);
                if (pos == string::npos) continue;
                if (growing[r]) {
                    // A match exists and reproduces itself forever.
                    tooMany = true;
                    break;
                }
                size_t start = 0;
                while (true) {
                    pos = cur.find(s1, start);
                    if (pos == string::npos) break;
                    string nxt = cur.substr(0, pos) + s2 + cur.substr(pos + s1.size());
                    if (visited.insert(nxt).second) {
                        work.push_back(nxt);
                        if (visited.size() > CAP) { tooMany = true; break; }
                    }
                    start = pos + 1;
                }
            }
        }
    }

    if (tooMany || visited.size() > CAP) {
        cout << "Too many." << endl;
    } else {
        cout << visited.size() << endl;
    }
    return 0;
}
