// POJ 3328 - Cliff Climbing
// Model: claude-sonnet-5
//
// State reduction: represent Jack's stance by (position of the foot that was
// placed most recently, which foot it is) instead of the full pair of foot
// positions. The rule "given a fixed foot's position, the OTHER foot must
// land in one of 9 blocks relative to it" means the next legal move depends
// only on the last-placed foot's position and identity -- the position the
// mover is leaving becomes irrelevant the instant it moves, since after the
// upcoming move the reference switches to the block just placed. Alternation
// (never move the same foot twice) falls out automatically because the
// stored foot-type flips every transition, and the invariant lx<rx is kept
// automatically because "left" moves always decrease the column relative to
// the fixed right foot and "right" moves always increase it.
//
// He starts by placing a single foot (his choice, left or right) on an 'S'
// block at zero cost; the discuss board's manual trace of sample 1 confirms
// this -- the accepted walkthrough only ever anchors moves off ONE placed
// foot, never requiring the other foot's real starting cell to be checked.
// So every 'S' cell is seeded as BOTH possible anchor types (foot=0: this
// block plays the left foot, next move places the right foot; foot=1:
// mirrored) at distance 0.
//
// Given an anchor (r,c,foot), the moving foot's 9 candidate offsets are
// generated by dc in {1,2,3} (foot=0, moving right foot, columns increase)
// or dc in {-1,-2,-3} (foot=1, moving left foot, columns decrease), with
// |dr| <= 3-|dc|, matching |lx-rx|+|ly-ry|<=3 with the 9-blocks figure.
// Edge cost is the value of the destination block ('S'/'T' cost 0, digits
// cost their value, 'X' is impassable).
//
// Dijkstra over states (row, col, footType) -- at most h*w*2 <= 60*30*2 =
// 3600 nodes, 9 edges each -- finds the minimum cost to first place a foot
// on a 'T' block; answer is the minimum distance over all states whose cell
// is 'T', or -1 if none reachable.
//
// Verified against all 5 samples (12, 5, -1, 22, 12), including the tricky
// width-2 cases (sample 2 vs 3, which differ only by one 'T' becoming 'X')
// and the width-10 all-S/all-T cases.

#include <cstdio>
#include <cstring>
#include <queue>
#include <vector>
using namespace std;

const int MAXH = 62, MAXW = 32;
const int INF = 1000000000;

int w, h;
char grid[MAXH][MAXW];
int dist_[MAXH][MAXW][2];

int cellCost(char ch) {
    if (ch == 'S' || ch == 'T') return 0;
    return ch - '0';
}

struct State {
    int d, r, c, f;
    State() : d(0), r(0), c(0), f(0) {}
    State(int d_, int r_, int c_, int f_) : d(d_), r(r_), c(c_), f(f_) {}
};
struct Cmp {
    bool operator()(const State &a, const State &b) const {
        return a.d > b.d;
    }
};

int main() {
    while (scanf("%d %d", &w, &h) == 2) {
        if (w == 0 && h == 0) break;
        for (int r = 0; r < h; r++) {
            for (int c = 0; c < w; c++) {
                char buf[8];
                scanf("%s", buf);
                grid[r][c] = buf[0];
            }
        }

        // direction lists
        vector<pair<int,int> > rightDirs, leftDirs; // (dr,dc)
        for (int dc = 1; dc <= 3; dc++) {
            int maxdr = 3 - dc;
            for (int dr = -maxdr; dr <= maxdr; dr++) {
                rightDirs.push_back(make_pair(dr, dc));
                leftDirs.push_back(make_pair(dr, -dc));
            }
        }

        for (int r = 0; r < h; r++)
            for (int c = 0; c < w; c++)
                dist_[r][c][0] = dist_[r][c][1] = INF;

        priority_queue<State, vector<State>, Cmp> pq;
        for (int c = 0; c < w; c++) {
            if (grid[h-1][c] == 'S') {
                for (int f = 0; f < 2; f++) {
                    if (dist_[h-1][c][f] > 0) {
                        dist_[h-1][c][f] = 0;
                        pq.push(State(0, h-1, c, f));
                    }
                }
            }
        }

        int answer = INF;
        while (!pq.empty()) {
            State cur = pq.top(); pq.pop();
            if (cur.d > dist_[cur.r][cur.c][cur.f]) continue;
            if (grid[cur.r][cur.c] == 'T') {
                if (cur.d < answer) answer = cur.d;
                continue; // no need to move further from a finish
            }
            const vector<pair<int,int> > &dirs = (cur.f == 0) ? rightDirs : leftDirs;
            int nf = 1 - cur.f;
            for (size_t i = 0; i < dirs.size(); i++) {
                int nr = cur.r + dirs[i].first;
                int nc = cur.c + dirs[i].second;
                if (nr < 0 || nr >= h || nc < 0 || nc >= w) continue;
                char ch = grid[nr][nc];
                if (ch == 'X') continue;
                int nd = cur.d + cellCost(ch);
                if (nd < dist_[nr][nc][nf]) {
                    dist_[nr][nc][nf] = nd;
                    pq.push(State(nd, nr, nc, nf));
                }
            }
        }

        if (answer >= INF) printf("-1\n");
        else printf("%d\n", answer);
    }
    return 0;
}
